Fixed the ensembl transcript gene_id and msigdb geneSet publication
bmeg/bmeg-etl pull request #379
Opened 2023-05-12 16:58 UTC by evergreen700

Unsure if the publication ID is the format you wanted but at least it's attached to the record now. I'll probably look at another record with publications next and make sure the numbers are able to match each other.

2023-05-15 21:56 UTC, evergreen700 commented
Pubmed:
- Changed the transform.yaml to be more flexible with different absrtract formats
- Changed the download files to work a little bit better. There is still a snakemake bug in there but that would probably be better addressed within the lathe source code.

2023-05-16 17:57 UTC, evergreen700 commented
Cellosarus:
- Obo reader modified slightly to capture species name but shouldn't affect execution of sifter file
- Sifter file modified to generate a "species" field that it then filters the samples by. This field is then discarded

2023-05-18 16:52 UTC, evergreen700 commented
BindingDB:
- Download.yaml fixed by removing name inconsistencies
- tsvParser.py created to handle the repeating columns at the end of the file
- transformTsv.yaml modified to read protien id's as a list instead of a single string, allows multiple protiens to be connected to a binding record
- protein_compound_association modified to add protein_structure property.

2023-05-19 17:47 UTC, kellrott requested changes

2023-05-19 17:47 UTC, kellrott commented on transform/bindingdb/.ipynb_checkpoints/download-checkpoint.yaml
Why is this file in the ipython notebook checkpoint directory?

2023-05-19 17:47 UTC, kellrott commented on transform/bindingdb/.ipynb_checkpoints/download-checkpoint.yaml
> +scripts:
Another file in the ipython checkpoint directory.

2023-05-19 17:47 UTC, kellrott commented on transform/bindingdb/.ipynb_checkpoints/download-checkpoint.yaml
> +scripts:
I'm trying to move download commands to the `prep` stanzas

2023-05-19 17:47 UTC, kellrott commented on transform/bindingdb/.ipynb_checkpoints/transform_tsv-checkpoint.yaml
> +    - from: bindingdb
Remember to clear out debug outputs once the script is done

2023-05-19 17:47 UTC, kellrott commented on transform/bindingdb/.ipynb_checkpoints/tsvParse-checkpoint.py
Is this file an artifact that was accidentally checked in?

2023-05-19 17:47 UTC, kellrott commented on transform/bindingdb/transform_tsv.yaml
> +      commandLine: ./tsvParse.py {{config.tsv}}
Lets put scripting in the `util` directory

2023-05-19 17:47 UTC, kellrott commented on transform/bindingdb/tsvParse.py
Move this to `util/`

2023-05-19 17:47 UTC, kellrott commented on transform/pubmed/download.yaml
> +scripts:
Leave this one as a prep command

2023-05-25 17:54 UTC, evergreen700 commented
Made the requested changes

2023-06-01 00:20 UTC, evergreen700 commented
PharmacoDB parse is on now!

2023-06-07 21:37 UTC, merged